name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: production
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check environment variables
      run: npm run build:check-env
      env:
        AUTH_DATABASE_URL: ${{ secrets.AUTH_DATABASE_URL }}
        HR_DATABASE_URL: ${{ secrets.HR_DATABASE_URL }}
        PAYROLL_DATABASE_URL: ${{ secrets.PAYROLL_DATABASE_URL }}
      
    - name: Generate Prisma clients
      run: npm run prisma:generate
      env:
        AUTH_DATABASE_URL: ${{ secrets.AUTH_DATABASE_URL }}
        HR_DATABASE_URL: ${{ secrets.HR_DATABASE_URL }}
        PAYROLL_DATABASE_URL: ${{ secrets.PAYROLL_DATABASE_URL }}
      
    - name: Build project
      run: npm run build
      env:
        AUTH_DATABASE_URL: ${{ secrets.AUTH_DATABASE_URL }}
        HR_DATABASE_URL: ${{ secrets.HR_DATABASE_URL }}
        PAYROLL_DATABASE_URL: ${{ secrets.PAYROLL_DATABASE_URL }}
        MAILTRAP_API_TOKEN: ${{ secrets.MAILTRAP_API_TOKEN }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
        NODE_ENV: production
        
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'
        working-directory: ./
      env:
        AUTH_DATABASE_URL: ${{ secrets.AUTH_DATABASE_URL }}
        HR_DATABASE_URL: ${{ secrets.HR_DATABASE_URL }}
        PAYROLL_DATABASE_URL: ${{ secrets.PAYROLL_DATABASE_URL }}
        MAILTRAP_API_TOKEN: ${{ secrets.MAILTRAP_API_TOKEN }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
        NODE_ENV: production

